### ISSUE TITLE
If you choose "None of the above" while also selecting other symptoms, the warning message says "Please select a response"

### ISSUE THREAD

**Issue by jdangerx** [ryananeff/medtracker#40]
Steps to reproduce:
1. Start a COVID screening survey.
2. Pick multiple symptoms including "None of the above."

It's good that this gets rejected, but the messaging could be a little clearer.

**Comment by ryananeff** [comment]
That's *strange. *Because there is no code that rejects that combination
specifically. In fact, if you select two other items and none of the above,
it still POSTs. Amazing catch!

You hit the nail on the head here though. I need to do some validation for
none of the above and also clear out the other responses.

**Comment by ryananeff** [comment]
Bug in parentheses, fix in pull request #43
